export const IPC_CHANNELS = {
  appGetVersion: "app:getVersion",
  directorySelectSource: "directory:selectSource",
  directorySelectTarget: "directory:selectTarget",
  targetListFolders: "target:listFolders",
  targetSetFolder: "target:setFolder",
  targetCreateFolder: "target:createFolder",
  folderLearningListNames: "folderLearning:listNames",
  documentsRefreshSource: "documents:refreshSource",
  previewGetData: "preview:getData",
  namingCreateInitialDraft: "naming:createInitialDraft",
  namingBuildProposal: "naming:buildProposal",
  namingCheckDestinationAvailability: "naming:checkDestinationAvailability",
  classificationPreparePlan: "classification:preparePlan",
  classificationExecute: "classification:execute",
  classificationUndoLast: "classification:undoLast",
  classificationGetLastUndoableAction: "classification:getLastUndoableAction",
  duplicatesAnalyzeExact: "duplicates:analyzeExact",
  extractionExtractPdfText: "extraction:extractPdfText",
  ocrGetStatus: "ocr:getStatus",
  ocrSelectTesseractExecutable: "ocr:selectTesseractExecutable",
  ocrSelectTessdataDirectory: "ocr:selectTessdataDirectory",
  ocrSaveSettings: "ocr:saveSettings",
  ocrTestEngine: "ocr:testEngine",
  ocrRunImage: "ocr:runImage",
  aiGetStatus: "ai:getStatus",
  aiGetSettings: "ai:getSettings",
  aiSaveSettings: "ai:saveSettings",
  aiTestConnection: "ai:testConnection",
  aiGetModelStatus: "ai:getModelStatus",
  aiPreloadModel: "ai:preloadModel",
  aiUnloadModel: "ai:unloadModel",
  aiRunSuggestion: "ai:runSuggestion",
  aiExportDiagnostic: "ai:exportDiagnostic",
  historyGetRecent: "history:getRecent"
} as const;

export const ALLOWED_IPC_CHANNELS = Object.values(IPC_CHANNELS);

export type IpcChannel = (typeof ALLOWED_IPC_CHANNELS)[number];
